# Generated by Django 6.0.7 on 2026-08-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SteamProfile',
            fields=[
                ('steamid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('personaName', models.CharField(default='', max_length=200)),
                ('avatar', models.URLField(default='', max_length=500)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
